#!/usr/bin/env python3
"""Compile the renderer's GLSL to a deterministic, embedded SPIR-V C header."""

import argparse
import pathlib
import struct
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", default="glslangValidator")
    parser.add_argument("--check", action="store_true", help="verify the checked-in header")
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parents[2]
    shaders = root / "src/restunts/platform/sdl3/shaders"
    lines = [
        "/* Generated by tools/scripts/generate-vulkan-shaders.py. Do not edit. */",
        "#ifndef RESTUNTS_VULKAN_SHADERS_H",
        "#define RESTUNTS_VULKAN_SHADERS_H",
        "",
    ]
    with tempfile.TemporaryDirectory(prefix="restunts-spirv-") as directory:
        for name in ("raster", "shade"):
            output = pathlib.Path(directory) / (name + ".spv")
            subprocess.run(
                [args.compiler, "-V", "--target-env", "vulkan1.0", "-Os",
                 "-o", str(output), str(shaders / (name + ".comp"))],
                check=True,
            )
            data = output.read_bytes()
            words = struct.unpack("<" + "I" * (len(data) // 4), data)
            lines.append("static const legacy_u32 restunts_vulkan_" + name + "_spv[] = {")
            for index in range(0, len(words), 6):
                lines.append("\t" + ", ".join(f"0x{word:08X}U" for word in words[index:index + 6]) + ",")
            lines.extend(["};", ""])
    lines.append("#endif")
    generated = ("\r\n".join(lines) + "\r\n").encode("ascii")
    # Run the project's formatter separately when updating its pinned version;
    # keep the generated arrays exempt from whitespace rewriting.
    generated = generated.replace(b"static const", b"// clang-format off\r\nstatic const", 1)
    generated = generated.replace(b"#endif", b"// clang-format on\r\n#endif")
    header = shaders / "vulkan_shaders.h"
    if args.check:
        if not header.exists() or header.read_bytes() != generated:
            raise SystemExit("Vulkan shaders are stale; regenerate with the documented compiler.")
    else:
        header.write_bytes(generated)


if __name__ == "__main__":
    main()
