#!/usr/bin/env python3
"""Rebuild Vulkan 1.0 SPIR-V with glslang 15.1.0; normal game builds need no SDK."""

import argparse
from pathlib import Path
import re
import struct
import subprocess
import tempfile

COMPILER_VERSION = "15.1.0"
TARGET_ENVIRONMENT = "vulkan1.0"
WORDS_PER_LINE = 7
REPOSITORY = Path(__file__).resolve().parents[2]
SHADER_DIRECTORY = REPOSITORY / "src/restunts/platform/sdl3/shaders"
OUTPUT = SHADER_DIRECTORY.parent / "hypervision_vulkan_shaders.h"
SHADERS = (
    ("vertex", "hypervision.vert", "vert", ()),
    ("surface", "hypervision.frag", "frag", ()),
    ("detail", "hypervision.frag", "frag", ("-DHV_DETAIL=1",)),
)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", default="glslangValidator")
    parser.add_argument("--validator", default="spirv-val")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    version = subprocess.check_output([args.compiler, "--version"], text=True)
    if not re.search(r"Glslang Version: \S*:" + re.escape(COMPILER_VERSION) + r"\s", version):
        parser.error(f"Reproducible generation requires glslang {COMPILER_VERSION}")
    lines = [
        "/* Generated by tools/scripts/generate-hypervision-shaders.py.",
        f" * glslang {COMPILER_VERSION}, --target-env {TARGET_ENVIRONMENT}; do not edit. */",
        "#ifndef RESTUNTS_HYPERVISION_VULKAN_SHADERS_H",
        "#define RESTUNTS_HYPERVISION_VULKAN_SHADERS_H",
        "",
        '#include "../../c/legacy.h"',
        "",
    ]
    with tempfile.TemporaryDirectory(prefix="restunts-hypervision-shaders-") as temporary:
        for name, source, stage, extra in SHADERS:
            output = Path(temporary) / f"{name}.spv"
            subprocess.run(
                [args.compiler, "-V", "--target-env", TARGET_ENVIRONMENT, "-S", stage,
                 "-e", "main", *extra, "-o", str(output), str(SHADER_DIRECTORY / source)],
                check=True,
            )
            subprocess.run([args.validator, "--target-env", TARGET_ENVIRONMENT, str(output)],
                           check=True)
            data = output.read_bytes()
            words = struct.unpack(f"<{len(data) // 4}I", data)
            lines.append(f"static const legacy_u32 hv_vulkan_{name}_spirv[] = {{")
            for first in range(0, len(words), WORDS_PER_LINE):
                lines.append("\t" + ", ".join(f"0x{word:08x}U" for word in
                                               words[first:first + WORDS_PER_LINE]) + ",")
            lines.extend(["};", ""])
    lines.extend(["#endif", ""])
    generated = "\r\n".join(lines).encode("utf-8")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != generated:
            raise SystemExit(f"Shader header differs: regenerate {OUTPUT.relative_to(REPOSITORY)}")
        print("HyperVision SPIR-V matches the pinned compiler output.")
    else:
        OUTPUT.write_bytes(generated)
        print(OUTPUT.relative_to(REPOSITORY))


if __name__ == "__main__":
    main()
