set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER aarch64-w64-mingw32-clang)
set(CMAKE_CXX_COMPILER aarch64-w64-mingw32-clang++)
set(CMAKE_RC_COMPILER aarch64-w64-mingw32-windres)
# LLVM-MinGW includes its Windows headers and libraries beside its compiler.
find_program(RESTUNTS_ARM64_COMPILER NAMES ${CMAKE_C_COMPILER} REQUIRED)
get_filename_component(restunts_compiler_directory "${RESTUNTS_ARM64_COMPILER}" DIRECTORY)
get_filename_component(restunts_toolchain_directory "${restunts_compiler_directory}" DIRECTORY)
set(CMAKE_FIND_ROOT_PATH "${restunts_toolchain_directory}/aarch64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
